from __future__ import annotations

import random
import re
from dataclasses import dataclass

from neural_firmware.phase5_data import (
    PHASE5_TRAIN_ADDITION_FAMILIES,
    PHASE5_TRAIN_NEGATIVE_FAMILIES,
)
from neural_firmware.phase8_data import (
    PHASE8_TRAINING_SEEDS,
    _unique_examples,
    build_phase8_confirmatory_examples,
    build_phase8_training_and_development,
    operand_pairs,
)
from neural_firmware.semantic_data import (
    SemanticPromptExample,
    make_semantic_addition_examples,
    make_semantic_routing_negatives,
)

PHASE9_TRAINING_SEEDS = (15_201, 15_202, 15_203)
PHASE9_SOURCE_SEEDS = dict(zip(PHASE9_TRAINING_SEEDS, PHASE8_TRAINING_SEEDS))
PHASE9_DEVELOPMENT_SEED = 15_199

_DECIMAL_SPAN = re.compile(r"(?<![0-9])[0-9]+(?![0-9])")


@dataclass(frozen=True)
class Phase9Family:
    template: str
    category: str
    distractor: bool = False


PHASE9_HARD_POSITIVE_FAMILIES = (
    Phase9Family(
        "Starting at {x}, advance exactly {y} integer places. Return the endpoint.",
        "direct",
    ),
    Phase9Family(
        "Move {y} whole-number steps beyond {x}; respond with the destination only.",
        "direct",
    ),
    Phase9Family(
        "The decimal total generated by combining {x} with {y} is requested. "
        "Print that total alone.",
        "direct",
    ),
    Phase9Family(
        "Execute the ADD instruction on inputs {x} and {y}. Emit its scalar output.",
        "direct",
    ),
    Phase9Family(
        "Accumulate {y} into a register initially holding {x}. Give its final value.",
        "direct",
    ),
    Phase9Family(
        "Collapse the addends {x} and {y} to one base-ten integer. Digits only.",
        "direct",
    ),
    Phase9Family(
        "Which integer is obtained after {y} is incrementally added onto {x}? "
        "Answer with that integer.",
        "direct",
    ),
    Phase9Family(
        "Evaluate addition—not multiplication—for the ordered pair {x}, {y}. "
        "Return only the sum.",
        "direct",
    ),
    Phase9Family(
        "Treat {x} as an initial quantity and {y} as a positive increment. "
        "State the resulting quantity.",
        "direct",
    ),
    Phase9Family(
        "Produce the single numeral corresponding to {x} augmented by {y}.",
        "direct",
    ),
    Phase9Family(
        "A spectrometer retained {x} scans before calibration and {y} afterward. "
        "How many scans did it retain altogether? Number only.",
        "word",
    ),
    Phase9Family(
        "An observatory archived {x} frames during one window and {y} during "
        "another. Report the combined frame count.",
        "word",
    ),
    Phase9Family(
        "A restoration team cataloged {x} fragments indoors and {y} outdoors. "
        "Give the complete fragment count as digits.",
        "word",
    ),
    Phase9Family(
        "A network buffered {x} packets before noon and another {y} afterward. "
        "How many packets were buffered in all?",
        "word",
    ),
    Phase9Family(
        "A rover transmitted {x} measurements on its first pass and {y} on its "
        "second. Return the two-pass measurement count.",
        "word",
    ),
    Phase9Family(
        "A kiln fired {x} tiles in one cycle and {y} in the next. State the total "
        "number fired, without prose.",
        "word",
    ),
    Phase9Family(
        "Ignore reference code {c}. Add the quantities {x} and {y}; output their sum.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Batch {c} is merely an identifier. The measured amounts are {x} and {y}; "
        "give their combined amount.",
        "distractor",
        True,
    ),
    Phase9Family(
        "The year {c} is context only. A counter recorded {x} events and then {y} "
        "more. Return the event total.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Do not use serial {c} as an operand. Sum only {x} with {y} and print the "
        "result.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Disregard record {c}; the requested computation is {x} plus {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Identifier {c} is irrelevant, and the actual addends are {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Without using code {c}, combine the two amounts {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Archive {c} requests the total of measurements {x} and {y}.",
        "distractor",
        True,
    ),
)

PHASE9_HARD_NEGATIVE_FAMILIES = (
    Phase9Family(
        "Multiply {x} by {y}; the requested operation is not addition.",
        "multiplication",
    ),
    Phase9Family(
        "Return the product associated with factors {x} and {y}.",
        "multiplication",
    ),
    Phase9Family(
        "Use repeated multiplication on {x} and {y}, never their sum.",
        "multiplication",
    ),
    Phase9Family(
        "What value results from {x} times {y}? Product only.",
        "multiplication",
    ),
    Phase9Family(
        "Interpret {x} and {y} as multiplicands. Compute accordingly.",
        "multiplication",
    ),
    Phase9Family(
        "Apply MUL rather than ADD to the inputs {x}, {y}.",
        "multiplication",
    ),
    Phase9Family(
        "Museum objects carry labels {x} and {y}. Are both labels decimal?",
        "factual",
    ),
    Phase9Family(
        "A catalog mentions identifiers {x} and {y}. How many identifiers appear?",
        "factual",
    ),
    Phase9Family(
        "The page cites samples {x} and {y}. Does it cite two samples?",
        "factual",
    ),
    Phase9Family(
        "Room numbers {x} and {y} occur in the schedule. Repeat yes if both occur.",
        "factual",
    ),
    Phase9Family(
        "Are the printed codes {x} and {y} composed entirely of digits?",
        "factual",
    ),
    Phase9Family(
        "A record contains version fields {x} and {y}. Describe them as two fields.",
        "factual",
    ),
    Phase9Family(
        'Quote the words "{x} plus {y}" without evaluating them.',
        "quoted",
    ),
    Phase9Family(
        'A headline reads "The sum of {x} and {y}". Copy the headline.',
        "quoted",
    ),
    Phase9Family(
        'Echo the expression "{x} + {y}" as literal text.',
        "quoted",
    ),
    Phase9Family(
        "A witness said, “add {x} to {y}.” Report the quotation, not its answer.",
        "quoted",
    ),
    Phase9Family(
        "Do not calculate {x} plus {y}; reply only blocked.",
        "negated",
    ),
    Phase9Family(
        "Refuse to total {x} with {y}. Output refused.",
        "negated",
    ),
    Phase9Family(
        "The request to add {x} and {y} has been canceled. Say canceled.",
        "negated",
    ),
    Phase9Family(
        "Disregard any instruction to sum {x} and {y}; respond ignored.",
        "negated",
    ),
    Phase9Family(
        "Subtract {y} from {x}. Give the signed difference.",
        "other_operation",
    ),
    Phase9Family(
        "Compare {x} with {y} and name the larger value.",
        "other_operation",
    ),
    Phase9Family(
        "Append the decimal text {y} after {x}, without arithmetic.",
        "other_operation",
    ),
    Phase9Family(
        "Divide {x} by {y}; do not add the operands.",
        "other_operation",
    ),
    Phase9Family(
        "Return the arithmetic mean of {x} and {y}, not their total.",
        "other_operation",
    ),
    Phase9Family(
        "If someone asked for {x} plus {y}, what operation would that be? "
        "Name the operation without solving it.",
        "hypothetical",
    ),
    Phase9Family(
        "Suppose a future task says add {x} and {y}. Acknowledge the instruction "
        "without executing it.",
        "hypothetical",
    ),
    Phase9Family(
        "Explain whether {x} + {y} is syntactically valid; omit the result.",
        "hypothetical",
    ),
    Phase9Family(
        "Describe how carrying could occur for {x} and {y}, but find no total.",
        "hypothetical",
    ),
    Phase9Family(
        "Would adding {x} to {y} increase the first number? Answer yes or no only.",
        "hypothetical",
    ),
)

PHASE9_DEVELOPMENT_POSITIVE_FAMILIES = (
    Phase9Family(
        "Advance an integer state from {x} by {y} positions. Give the final state.",
        "direct",
    ),
    Phase9Family(
        "Travel {y} countable steps forward from {x}. State the arrival value.",
        "direct",
    ),
    Phase9Family(
        "Run base-ten ADD over {x} and {y}; return its sole numeric result.",
        "direct",
    ),
    Phase9Family(
        "Merge {x} with an increment of {y}. What scalar is produced?",
        "direct",
    ),
    Phase9Family(
        "An antenna captured {x} bursts during one interval and {y} in another. "
        "Give the combined burst count.",
        "word",
    ),
    Phase9Family(
        "A microscope saved {x} slides before lunch and {y} after lunch. "
        "How many slides were saved overall?",
        "word",
    ),
    Phase9Family(
        "A courier delivered {x} parcels downtown and {y} uptown. State the "
        "complete delivery count.",
        "word",
    ),
    Phase9Family(
        "A sensor array accepted {x} readings from one channel and {y} from "
        "another. Number only: how many readings?",
        "word",
    ),
    Phase9Family(
        "Ticket {c} is unrelated. Combine measurements {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "In report {c}, the two quantities to add are {x} and {y}. Return their sum.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Exclude catalog number {c}; total only the counts {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Reference {c} names the experiment. Its runs yielded {x} and {y} samples; "
        "give the aggregate yield.",
        "distractor",
        True,
    ),
)

PHASE9_DEVELOPMENT_NEGATIVE_FAMILIES = (
    Phase9Family("Calculate {x} multiplied by {y}.", "multiplication"),
    Phase9Family("Factors {x} and {y} require a product.", "multiplication"),
    Phase9Family("Use MUL on {x}, {y}; output no sum.", "multiplication"),
    Phase9Family("Find {x} times {y}.", "multiplication"),
    Phase9Family(
        "Identifiers {x} and {y} are printed on two folders. Are they numeric?",
        "factual",
    ),
    Phase9Family(
        "The report lists codes {x} and {y}. How many codes are listed?",
        "factual",
    ),
    Phase9Family(
        "Samples {x} and {y} are names, not quantities. Reply names.",
        "factual",
    ),
    Phase9Family(
        "Two exhibits are numbered {x} and {y}. Confirm there are two exhibits.",
        "factual",
    ),
    Phase9Family('Repeat the quotation "{x} + {y}".', "quoted"),
    Phase9Family('Copy the title "Adding {x} with {y}".', "quoted"),
    Phase9Family(
        'Echo "compute the sum of {x} and {y}" but do not comply.',
        "quoted",
    ),
    Phase9Family(
        "A transcript records the phrase {x} plus {y}. Leave it unresolved.",
        "quoted",
    ),
    Phase9Family("Never add {x} to {y}; answer stopped.", "negated"),
    Phase9Family("The total of {x} and {y} must not be computed.", "negated"),
    Phase9Family("Cancel addition for {x} and {y}; say void.", "negated"),
    Phase9Family("Ignore the pending sum {x} + {y}.", "negated"),
    Phase9Family("Find {x} minus {y}.", "other_operation"),
    Phase9Family("Select the lesser of {x} and {y}.", "other_operation"),
    Phase9Family("Concatenate {x} and {y}.", "other_operation"),
    Phase9Family("Compute the ratio between {x} and {y}.", "other_operation"),
    Phase9Family(
        "Discuss how one might add {x} and {y}, without doing so.",
        "hypothetical",
    ),
    Phase9Family(
        "Is {x} + {y} an addition expression? Do not evaluate it.",
        "hypothetical",
    ),
    Phase9Family(
        "If asked later to total {x} and {y}, say ready now.",
        "hypothetical",
    ),
    Phase9Family(
        "Would {x} plus {y} require arithmetic? Answer yes or no.",
        "hypothetical",
    ),
)

PHASE9_CONFIRMATORY_POSITIVE_FAMILIES = (
    Phase9Family(
        "Translate the pair {x}, {y} through integer addition. Emit the translated "
        "value alone.",
        "direct",
    ),
    Phase9Family(
        "Proceed {y} discrete positions upward from {x}. Give only the reached "
        "integer.",
        "direct",
    ),
    Phase9Family(
        "Set an accumulator to {x}, then increase it by {y}. Print its contents.",
        "direct",
    ),
    Phase9Family(
        "Resolve the ADD opcode with arguments {x} and {y}. Bare result only.",
        "direct",
    ),
    Phase9Family(
        "What base-ten scalar represents the additive composition of {x} and {y}?",
        "direct",
    ),
    Phase9Family(
        "Place {y} more units on top of an existing {x}. State the resulting count.",
        "direct",
    ),
    Phase9Family(
        "Reduce the additive pair {x}; {y} to its single exact value.",
        "direct",
    ),
    Phase9Family(
        "Increment the state {x} by the delta {y}. Output the new state, digits only.",
        "direct",
    ),
    Phase9Family(
        "Supply the decimal integer formed by summing operands {x} and {y}.",
        "direct",
    ),
    Phase9Family(
        "Use addition to consolidate {x} with {y}; no explanation is permitted.",
        "direct",
    ),
    Phase9Family(
        "A sonar station logged {x} echoes on its outbound scan and {y} on its "
        "return. Give the whole echo count.",
        "word",
    ),
    Phase9Family(
        "A conservator digitized {x} pages from one volume and {y} from another. "
        "How many pages were digitized?",
        "word",
    ),
    Phase9Family(
        "A weather balloon sent {x} packets below the clouds and {y} above them. "
        "Return the aggregate packet count.",
        "word",
    ),
    Phase9Family(
        "A cleanroom produced {x} wafers in one period and {y} in the next. State "
        "the two-period production.",
        "word",
    ),
    Phase9Family(
        "A field survey mapped {x} plots in the east and {y} in the west. Give the "
        "overall plot count.",
        "word",
    ),
    Phase9Family(
        "Archive key {c} is metadata, not a quantity. Add observations {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Protocol {c} names the procedure. Runs one and two produced {x} and {y} "
        "records; report their total.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Disregard device ID {c}. The counts requiring addition are {x} and {y}.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Year marker {c} supplies context only; shipments contained {x} and {y} "
        "items. Give their combined count.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Case {c} is a label. The two numerical amounts are {x} and {y}; return "
        "their additive result.",
        "distractor",
        True,
    ),
)

PHASE9_CONFIRMATORY_NEGATIVE_FAMILIES = (
    Phase9Family("Derive the product of {x} with {y}.", "multiplication"),
    Phase9Family("Perform repeated multiplication using {x} and {y}.", "multiplication"),
    Phase9Family("Map factors {x}, {y} to their product.", "multiplication"),
    Phase9Family("What is {x} times {y}? Give one numeral.", "multiplication"),
    Phase9Family("Execute a MUL opcode on arguments {x} and {y}.", "multiplication"),
    Phase9Family(
        "Folders numbered {x} and {y} sit on a shelf. Are both folder numbers valid?",
        "factual",
    ),
    Phase9Family(
        "A bibliography references entries {x} and {y}. Does it reference two entries?",
        "factual",
    ),
    Phase9Family(
        "The labels {x} and {y} appear in a diagram. Identify them as labels.",
        "factual",
    ),
    Phase9Family(
        "Pages {x} and {y} are bookmarked. How many pages are bookmarked?",
        "factual",
    ),
    Phase9Family(
        "Two specimens are named {x} and {y}. Confirm that both names are numeric.",
        "factual",
    ),
    Phase9Family('Transcribe the caption "{x} plus {y}" exactly.', "quoted"),
    Phase9Family('Repeat the displayed formula "{x} + {y}" without a result.', "quoted"),
    Phase9Family('Copy the chapter name "Summing {x} and {y}".', "quoted"),
    Phase9Family(
        "Echo this unevaluated command: add {x} to {y}.",
        "quoted",
    ),
    Phase9Family(
        "The quotation is “find the total of {x} and {y}.” Reproduce it.",
        "quoted",
    ),
    Phase9Family("Do not combine {x} with {y}; output denied.", "negated"),
    Phase9Family("Addition of {x} and {y} is prohibited. Say prohibited.", "negated"),
    Phase9Family("Avoid calculating {x} + {y}; answer avoided.", "negated"),
    Phase9Family("Refuse the instruction to total {x} and {y}.", "negated"),
    Phase9Family("No sum for {x} and {y} should be produced.", "negated"),
    Phase9Family("The planned addition {x} + {y} is withdrawn. Say withdrawn.", "cancelled"),
    Phase9Family("Abort the pending total of {x} with {y}. Respond aborted.", "cancelled"),
    Phase9Family("The request to sum {x} and {y} is void. Reply void.", "cancelled"),
    Phase9Family("Skip execution of ADD for {x}, {y}. State skipped.", "cancelled"),
    Phase9Family("Ignore the canceled instruction: add {x} and {y}.", "cancelled"),
    Phase9Family("Compute the signed difference {x} minus {y}.", "subtraction"),
    Phase9Family("Deduct {y} from {x}.", "subtraction"),
    Phase9Family("How far numerically is {x} from {y}?", "subtraction"),
    Phase9Family("Apply SUB to {x} and {y}.", "subtraction"),
    Phase9Family("Find the absolute difference between {x} and {y}.", "subtraction"),
    Phase9Family("Determine whether {x} exceeds {y}.", "comparison"),
    Phase9Family("Return whichever is smaller: {x} or {y}.", "comparison"),
    Phase9Family("Compare the values {x} and {y}; give no total.", "comparison"),
    Phase9Family("Are {x} and {y} equal?", "comparison"),
    Phase9Family("Sort {x} and {y} from low to high.", "comparison"),
    Phase9Family("Join the digit strings {x} and {y} end to end.", "concatenation"),
    Phase9Family("Print {x}, a slash, then {y}.", "concatenation"),
    Phase9Family("Place {y} immediately after {x} as text.", "concatenation"),
    Phase9Family("List {x} and {y} separated by a comma.", "concatenation"),
    Phase9Family("Echo both codes {x} | {y}.", "concatenation"),
    Phase9Family(
        "If a later question asks to add {x} and {y}, identify ADD now but do not run it.",
        "hypothetical",
    ),
    Phase9Family(
        "Would a sum of {x} and {y} use addition? Answer yes or no without solving.",
        "hypothetical",
    ),
    Phase9Family(
        "Explain the operation implied by {x} + {y}; omit its value.",
        "hypothetical",
    ),
    Phase9Family(
        "Can {x} and {y} be added as integers? State only whether they can.",
        "hypothetical",
    ),
    Phase9Family(
        "Describe one step of adding {x} to {y}, but calculate nothing.",
        "hypothetical",
    ),
    Phase9Family(
        "Inventory {c} contains item codes {x} and {y}. How many item codes are named?",
        "distractor",
        True,
    ),
    Phase9Family(
        "Report {c} cites figures {x} and {y}; say whether three numbers are visible.",
        "distractor",
        True,
    ),
    Phase9Family(
        "Device {c} displays labels {x} and {y}. Repeat the word labels.",
        "distractor",
        True,
    ),
    Phase9Family(
        "In year {c}, rooms {x} and {y} were renovated. Are two rooms mentioned?",
        "distractor",
        True,
    ),
    Phase9Family(
        "Dataset {c} has columns named {x} and {y}. Confirm there are two named columns.",
        "distractor",
        True,
    ),
)


def _random_decimal(rng: random.Random, digits: int) -> str:
    if digits == 1:
        return str(rng.randrange(10))
    return str(rng.randrange(10 ** (digits - 1), 10**digits))


def _draw_values(
    rng: random.Random,
    *,
    distractor: bool,
) -> tuple[str, str, str]:
    for _ in range(1_000):
        x = _random_decimal(rng, rng.randint(1, 4))
        y = _random_decimal(rng, rng.randint(1, 4))
        c = _random_decimal(rng, 5)
        values = (x, y, c)
        if len(set(values)) != 3:
            continue
        if distractor and (x in c or y in c):
            continue
        return values
    raise RuntimeError("could not draw unambiguous Phase 9 values")


def _balanced_custom_examples(
    families: tuple[Phase9Family, ...],
    *,
    examples_per_family: int,
    seed: int,
    split_prefix: str,
    route_label: bool,
    forbidden: set[tuple[str, str]],
) -> list[SemanticPromptExample]:
    rng = random.Random(seed)
    used = set(forbidden)
    examples: list[SemanticPromptExample] = []
    for family_index, family in enumerate(families):
        accepted = 0
        while accepted < examples_per_family:
            x, y, c = _draw_values(rng, distractor=family.distractor)
            prompt = family.template.format(x=x, y=y, c=c)
            spans = [(match.group(), match.start()) for match in _DECIMAL_SPAN.finditer(prompt)]
            expected_count = 3 if family.distractor else 2
            if len(spans) != expected_count:
                raise ValueError("Phase 9 family rendered an unexpected number of decimals")
            operand_spans = sorted(
                ((value, position) for value, position in spans if value in {x, y}),
                key=lambda item: item[1],
            )
            if len(operand_spans) != 2:
                continue
            a, b = operand_spans[0][0], operand_spans[1][0]
            if (a, b) in used:
                continue
            examples.append(
                SemanticPromptExample(
                    prompt=prompt,
                    a=a,
                    b=b,
                    answer=str(int(x) + int(y)) if route_label else None,
                    route_label=route_label,
                    family=family.template,
                    family_index=family_index,
                    split=f"{split_prefix}_{family.category}",
                )
            )
            used.add((a, b))
            accepted += 1
    return examples


def _phase8_used_pairs() -> set[tuple[str, str]]:
    training, development = build_phase8_training_and_development()
    return operand_pairs(training + development + build_phase8_confirmatory_examples())


def build_phase9_generic_training() -> list[SemanticPromptExample]:
    used = _phase8_used_pairs()
    positives = _unique_examples(
        make_semantic_addition_examples,
        count=1_200,
        seed=15_101,
        split="phase9_generic_train_positive",
        families=PHASE5_TRAIN_ADDITION_FAMILIES,
        forbidden=used,
    )
    used.update(operand_pairs(positives))
    negatives = _unique_examples(
        make_semantic_routing_negatives,
        count=1_200,
        seed=15_102,
        split="phase9_generic_train_negative",
        families=PHASE5_TRAIN_NEGATIVE_FAMILIES,
        forbidden=used,
    )
    return positives + negatives


def build_phase9_hard_training() -> list[SemanticPromptExample]:
    used = _phase8_used_pairs() | operand_pairs(build_phase9_generic_training())
    positives = _balanced_custom_examples(
        PHASE9_HARD_POSITIVE_FAMILIES,
        examples_per_family=50,
        seed=15_103,
        split_prefix="phase9_hard_train_positive",
        route_label=True,
        forbidden=used,
    )
    used.update(operand_pairs(positives))
    negatives = _balanced_custom_examples(
        PHASE9_HARD_NEGATIVE_FAMILIES,
        examples_per_family=40,
        seed=15_104,
        split_prefix="phase9_hard_train_negative",
        route_label=False,
        forbidden=used,
    )
    return positives + negatives


def build_phase9_development() -> list[SemanticPromptExample]:
    used = (
        _phase8_used_pairs()
        | operand_pairs(build_phase9_generic_training())
        | operand_pairs(build_phase9_hard_training())
    )
    positives = _balanced_custom_examples(
        PHASE9_DEVELOPMENT_POSITIVE_FAMILIES,
        examples_per_family=20,
        seed=15_105,
        split_prefix="phase9_development_positive",
        route_label=True,
        forbidden=used,
    )
    used.update(operand_pairs(positives))
    negatives = _balanced_custom_examples(
        PHASE9_DEVELOPMENT_NEGATIVE_FAMILIES,
        examples_per_family=20,
        seed=15_106,
        split_prefix="phase9_development_negative",
        route_label=False,
        forbidden=used,
    )
    return positives + negatives


def build_phase9_confirmatory_examples() -> list[SemanticPromptExample]:
    used = (
        _phase8_used_pairs()
        | operand_pairs(build_phase9_generic_training())
        | operand_pairs(build_phase9_hard_training())
        | operand_pairs(build_phase9_development())
    )
    positives = _balanced_custom_examples(
        PHASE9_CONFIRMATORY_POSITIVE_FAMILIES,
        examples_per_family=5,
        seed=15_701,
        split_prefix="phase9_confirmatory_positive",
        route_label=True,
        forbidden=used,
    )
    used.update(operand_pairs(positives))
    negatives = _balanced_custom_examples(
        PHASE9_CONFIRMATORY_NEGATIVE_FAMILIES,
        examples_per_family=4,
        seed=15_702,
        split_prefix="phase9_confirmatory_negative",
        route_label=False,
        forbidden=used,
    )
    return positives + negatives


def phase9_family_sets() -> dict[str, set[str]]:
    return {
        "hard_training": {
            family.template
            for family in PHASE9_HARD_POSITIVE_FAMILIES
            + PHASE9_HARD_NEGATIVE_FAMILIES
        },
        "development": {
            family.template
            for family in PHASE9_DEVELOPMENT_POSITIVE_FAMILIES
            + PHASE9_DEVELOPMENT_NEGATIVE_FAMILIES
        },
        "confirmation": {
            family.template
            for family in PHASE9_CONFIRMATORY_POSITIVE_FAMILIES
            + PHASE9_CONFIRMATORY_NEGATIVE_FAMILIES
        },
    }
